/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.lab;
import com.mycompany.lab.Grafo;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Alann
 */
public class GrafoMatriz extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GrafoMatriz.class.getName());

    private Grafo grafo = new Grafo();
    private PanelGrafo dibujo;
    private boolean modoAgregar = false;
    private boolean modoConectar = false;
    private int nodoSeleccionado = -1;
        /**me 
     * Creates new form GrafoMatriz
     */
   
    public GrafoMatriz() {
    initComponents();

    dibujo = new PanelGrafo(grafo);

    panelDibujo.setLayout(new java.awt.BorderLayout());
    panelDibujo.add(dibujo, java.awt.BorderLayout.CENTER);

    panelDibujo.revalidate();
    panelDibujo.repaint();

    dibujo.addMouseListener(new java.awt.event.MouseAdapter() {

        @Override
        public void mouseClicked(java.awt.event.MouseEvent evt) {

            if (modoAgregar) {

                int x = evt.getX();
                int y = evt.getY();

                int cantidad = grafo.getNodos().size();

                String nombre = String.valueOf(
                    (char) ('A' + cantidad)
                );

                Nodo nodo = new Nodo(nombre, x, y);
                grafo.agregarNodo(nodo);

                dibujo.repaint();
            }else if (modoConectar) {

    int x = evt.getX();
    int y = evt.getY();

    for (int i = 0; i < grafo.getNodos().size(); i++) {

        Nodo nodo = grafo.getNodos().get(i);

        double distancia = Math.sqrt(
            Math.pow(x - nodo.getX(), 2)
            + Math.pow(y - nodo.getY(), 2)
        );

        if (distancia <= 20) {

            if (nodoSeleccionado == -1) {

                nodoSeleccionado = i;

            } else {

                grafo.agregarArista(nodoSeleccionado, i);

                nodoSeleccionado = -1;

                dibujo.repaint();
            }

            break;
        }
    }
}
        }
    });
}
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAgregarNodo = new javax.swing.JButton();
        btnConectar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        panelDibujo = new javax.swing.JPanel();
        btnGenerarMatriz = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaMatriz = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtLista = new javax.swing.JTextArea();
        btnBFS = new javax.swing.JButton();
        btnDFS = new javax.swing.JButton();
        txtRecorrido = new javax.swing.JTextField();
        btnVolver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnAgregarNodo.setText("Agregar Nodos");
        btnAgregarNodo.addActionListener(this::btnAgregarNodoActionPerformed);

        btnConectar.setText("Conectar");
        btnConectar.addActionListener(this::btnConectarActionPerformed);

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(this::btnLimpiarActionPerformed);

        panelDibujo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout panelDibujoLayout = new javax.swing.GroupLayout(panelDibujo);
        panelDibujo.setLayout(panelDibujoLayout);
        panelDibujoLayout.setHorizontalGroup(
            panelDibujoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 329, Short.MAX_VALUE)
        );
        panelDibujoLayout.setVerticalGroup(
            panelDibujoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 183, Short.MAX_VALUE)
        );

        btnGenerarMatriz.setText("Generar matriz");
        btnGenerarMatriz.addActionListener(this::btnGenerarMatrizActionPerformed);

        tablaMatriz.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaMatriz);

        jLabel1.setText("Lista de adyacencia");

        txtLista.setColumns(20);
        txtLista.setRows(5);
        jScrollPane2.setViewportView(txtLista);

        btnBFS.setText("BFS");
        btnBFS.addActionListener(this::btnBFSActionPerformed);

        btnDFS.setText("DFS");
        btnDFS.addActionListener(this::btnDFSActionPerformed);

        txtRecorrido.setEditable(false);
        txtRecorrido.addActionListener(this::txtRecorridoActionPerformed);

        btnVolver.setText("Volver");
        btnVolver.addActionListener(this::btnVolverActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnDFS)
                    .addComponent(btnBFS)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(btnLimpiar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnConectar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnAgregarNodo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(btnGenerarMatriz))
                                .addGap(54, 54, 54))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtRecorrido, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(panelDibujo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(140, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnVolver)
                .addGap(31, 31, 31))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(btnAgregarNodo)
                        .addGap(17, 17, 17)
                        .addComponent(btnConectar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnLimpiar))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(panelDibujo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnGenerarMatriz)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabel1))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addComponent(btnBFS)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtRecorrido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(btnDFS)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addComponent(btnVolver)
                .addGap(17, 17, 17))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBFSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBFSActionPerformed
        // TODO add your handling code here:
        if (grafo.getNodos().isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(
        this, "Primero debe agregar nodos."
        );
        return;
        }

        String recorrido = grafo.recorridoAnchura(0);
        txtRecorrido.setText(recorrido);
    }//GEN-LAST:event_btnBFSActionPerformed

    private void btnAgregarNodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarNodoActionPerformed
        // TODO add your handling code here:
        modoAgregar = true;
        modoConectar = false;

        javax.swing.JOptionPane.showMessageDialog(
        this, "Haz clic en el panel para agregar nodos."
);
    }//GEN-LAST:event_btnAgregarNodoActionPerformed

    private void btnConectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConectarActionPerformed
        // TODO add your handling code here:
        modoAgregar = false;
        modoConectar = true;
        nodoSeleccionado = -1;

javax.swing.JOptionPane.showMessageDialog(
    this, "Seleccione dos nodos para conectarlos."
);
    }//GEN-LAST:event_btnConectarActionPerformed

    private void btnGenerarMatrizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarMatrizActionPerformed
        // TODO add your handling code here:
            int cantidad = grafo.getNodos().size();

    if (cantidad == 0) {
        javax.swing.JOptionPane.showMessageDialog(
            this, "Primero debe agregar nodos."
        );
        return;
    }

    // Obtener la matriz del grafo
    int[][] matriz = grafo.getMatrizAdyacencia();

    // Crear nombres de las columnas
    String[] columnas = new String[cantidad];

    for (int i = 0; i < cantidad; i++) {
        columnas[i] = grafo.getNodos().get(i).getNombre();
    }

    // Crear los datos de la tabla
    Object[][] datos = new Object[cantidad][cantidad];

    for (int i = 0; i < cantidad; i++) {
        for (int j = 0; j < cantidad; j++) {
            datos[i][j] = matriz[i][j];
        }
    }

    // Mostrar la matriz
    DefaultTableModel modelo =
            new DefaultTableModel(datos, columnas) {
        @Override
        public boolean isCellEditable(int fila, int columna) {
            return false;
        }
};

    tablaMatriz.setModel(modelo);

    // Mostrar la lista de adyacencia
    txtLista.setText(grafo.generarListaAdyacencia());
    }//GEN-LAST:event_btnGenerarMatrizActionPerformed

    private void btnDFSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDFSActionPerformed
        // TODO add your handling code here:
        if (grafo.getNodos().isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(
        this, "Primero debe agregar nodos."
        );
        return;
        }

        String recorrido = grafo.recorridoProfundidad(0);
        txtRecorrido.setText(recorrido);
    }//GEN-LAST:event_btnDFSActionPerformed

    private void txtRecorridoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRecorridoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRecorridoActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:
        grafo = new Grafo();

        dibujo.setGrafo(grafo);
        dibujo.repaint();

        tablaMatriz.setModel(
        new javax.swing.table.DefaultTableModel()
        );

        txtLista.setText("");
        txtRecorrido.setText("");

        modoAgregar = false;
        modoConectar = false;
        nodoSeleccionado = -1;
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        // TODO add your handling code here:
        Principal ventana = new Principal();

        ventana.setLocationRelativeTo(null);
        ventana.setVisible(true);

        this.dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new GrafoMatriz().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarNodo;
    private javax.swing.JButton btnBFS;
    private javax.swing.JButton btnConectar;
    private javax.swing.JButton btnDFS;
    private javax.swing.JButton btnGenerarMatriz;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel panelDibujo;
    private javax.swing.JTable tablaMatriz;
    private javax.swing.JTextArea txtLista;
    private javax.swing.JTextField txtRecorrido;
    // End of variables declaration//GEN-END:variables
}
