/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.lab;
import com.mycompany.lab.Grafo;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Alann
 */
public class MatrizGrafo extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MatrizGrafo.class.getName());
    private Grafo grafo;
    /**
     * Creates new form MatrizGrafo
     */
    public MatrizGrafo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtCantidad = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnGenerarMatriz = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaMatriz = new javax.swing.JTable();
        btnGenerarGrafo = new javax.swing.JButton();
        panelDibujo = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtLista = new javax.swing.JTextArea();
        btnBFS = new javax.swing.JButton();
        btnDFS = new javax.swing.JButton();
        txtRecorrido = new javax.swing.JTextField();
        btnVolver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setText("Cantidad de nodos");

        btnGenerarMatriz.setText("Generar Matriz");
        btnGenerarMatriz.addActionListener(this::btnGenerarMatrizActionPerformed);

        tablaMatriz.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaMatriz);

        btnGenerarGrafo.setText("Generar Grafo");
        btnGenerarGrafo.addActionListener(this::btnGenerarGrafoActionPerformed);

        panelDibujo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout panelDibujoLayout = new javax.swing.GroupLayout(panelDibujo);
        panelDibujo.setLayout(panelDibujoLayout);
        panelDibujoLayout.setHorizontalGroup(
            panelDibujoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 231, Short.MAX_VALUE)
        );
        panelDibujoLayout.setVerticalGroup(
            panelDibujoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 98, Short.MAX_VALUE)
        );

        jLabel3.setText("Lista de adyacencia");

        txtLista.setEditable(false);
        txtLista.setColumns(20);
        txtLista.setRows(5);
        jScrollPane2.setViewportView(txtLista);

        btnBFS.setText("BFS");
        btnBFS.addActionListener(this::btnBFSActionPerformed);

        btnDFS.setText("DFS");
        btnDFS.addActionListener(this::btnDFSActionPerformed);

        btnVolver.setText("Volver");
        btnVolver.addActionListener(this::btnVolverActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnDFS)
                    .addComponent(btnBFS)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnGenerarMatriz)
                                    .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnGenerarGrafo))
                                .addGap(8, 8, 8))
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(panelDibujo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 67, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(txtRecorrido, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnVolver)
                .addGap(34, 34, 34))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(4, 4, 4)
                        .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnGenerarMatriz))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelDibujo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGenerarGrafo))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addComponent(btnBFS)
                .addGap(2, 2, 2)
                .addComponent(txtRecorrido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(btnDFS)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addComponent(btnVolver)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGenerarGrafoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarGrafoActionPerformed
        // TODO add your handling code here:
        try {
            if (tablaMatriz.isEditing()) {
                tablaMatriz.getCellEditor().stopCellEditing();
            }

            int cantidad = tablaMatriz.getRowCount();
            int[][] matriz = new int[cantidad][cantidad];

            for (int i = 0; i < cantidad; i++) {
                for (int j = 0; j < cantidad; j++) {

                    int valor = Integer.parseInt(
                        tablaMatriz.getValueAt(i, j).toString()
                    );

                    if (valor != 0 && valor != 1) {
                        throw new IllegalArgumentException(
                            "Solo se permiten 0 y 1."
                        );
                    }

                    matriz[i][j] = valor;
                }
            }

            // Trabajaremos con grafos no dirigidos.
            for (int i = 0; i < cantidad; i++) {
                for (int j = 0; j < cantidad; j++) {
                    if (matriz[i][j] != matriz[j][i]) {
                        throw new IllegalArgumentException(
                            "La matriz debe ser simétrica."
                        );
                    }
                }
            }

            grafo = new Grafo();

            int centroX = panelDibujo.getWidth() / 2;
            int centroY = panelDibujo.getHeight() / 2;
            int radio = Math.max(0,
                Math.min(centroX, centroY) - 30
            );

            for (int i = 0; i < cantidad; i++) {

                double angulo = 2 * Math.PI * i / cantidad;

                int x = centroX + (int)(radio * Math.cos(angulo));
                int y = centroY + (int)(radio * Math.sin(angulo));

                Nodo nodo = new Nodo(
                    String.valueOf((char)('A' + i)), x, y
                );

                grafo.agregarNodo(nodo);
            }

            grafo.establecerMatriz(matriz);

            PanelGrafo dibujo = new PanelGrafo(grafo);

            panelDibujo.removeAll();
            panelDibujo.setLayout(new java.awt.BorderLayout());

            dibujo.setPreferredSize(new java.awt.Dimension(320, 200));
            panelDibujo.setPreferredSize(new java.awt.Dimension(320, 200));

            panelDibujo.add(dibujo, java.awt.BorderLayout.CENTER);

            panelDibujo.revalidate();
            panelDibujo.repaint();

            this.pack();
            this.setLocationRelativeTo(null);

            txtLista.setText(grafo.generarListaAdyacencia());

        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(
                this, "Ingrese solamente números 0 y 1."
            );
        } catch (IllegalArgumentException e) {
            javax.swing.JOptionPane.showMessageDialog(
                this, e.getMessage()
            );
        }
    }//GEN-LAST:event_btnGenerarGrafoActionPerformed

    private void btnBFSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBFSActionPerformed
        // TODO add your handling code here:
        if (grafo == null) {
        javax.swing.JOptionPane.showMessageDialog(
            this, "Primero debe generar el grafo."
        );
        return;
    }

        String recorrido = grafo.recorridoAnchura(0);
        txtRecorrido.setText(recorrido);
    }//GEN-LAST:event_btnBFSActionPerformed

    private void btnGenerarMatrizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarMatrizActionPerformed
        // TODO add your handling code here: try {
        try {

    int cantidad = Integer.parseInt(txtCantidad.getText());

    if (cantidad <= 0) {
        JOptionPane.showMessageDialog(this,
                "La cantidad de nodos debe ser mayor que 0.");
        return;
    }

    String[] columnas = new String[cantidad];

    for (int i = 0; i < cantidad; i++) {
        columnas[i] = String.valueOf((char) ('A' + i));
    }

    Object[][] datos = new Object[cantidad][cantidad];

    for (int i = 0; i < cantidad; i++) {
        for (int j = 0; j < cantidad; j++) {
            datos[i][j] = 0;
        }
    }

    DefaultTableModel modelo =
            new DefaultTableModel(datos, columnas);

    tablaMatriz.setModel(modelo);

} catch (NumberFormatException e) {

    JOptionPane.showMessageDialog(this,
            "Ingrese una cantidad válida de nodos.");
}

    
    }//GEN-LAST:event_btnGenerarMatrizActionPerformed

    private void btnDFSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDFSActionPerformed
        // TODO add your handling code here:
        if (grafo == null) {
        javax.swing.JOptionPane.showMessageDialog(
        this, "Primero debe generar el grafo."
        );
        return;
        }

        String recorrido = grafo.recorridoProfundidad(0);
        txtRecorrido.setText(recorrido);
    }//GEN-LAST:event_btnDFSActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        // TODO add your handling code here:
        Principal ventana = new Principal();

        ventana.setLocationRelativeTo(null);
        ventana.setVisible(true);

        this.dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

    
  
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MatrizGrafo().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBFS;
    private javax.swing.JButton btnDFS;
    private javax.swing.JButton btnGenerarGrafo;
    private javax.swing.JButton btnGenerarMatriz;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel panelDibujo;
    private javax.swing.JTable tablaMatriz;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextArea txtLista;
    private javax.swing.JTextField txtRecorrido;
    // End of variables declaration//GEN-END:variables
}
